### ISSUE TITLE
Map Field: Failed to get the type for *.location. Setting to "never".

### ISSUE THREAD

**Issue by olivermack** [ChappIO/directus-extension-models#14]
Cheers,

just fiddling around with this lib and stumbled upon an issue when having a `Map` type field. Guess it is just missing an appropriate translation.

https://docs.directus.io/app/data-model/fields/selection.html#map

Here's a snippet (obfuscated) from my schema dump:

```yaml
  - collection: [SNIP]
    field: location
    type: geometry.Point
    meta:
      collection: [SNIP]
      conditions: null
      display: null
      display_options: null
      field: location
      group: null
      hidden: false
      interface: map
      note: null
      options:
        defaultView:
          bearing: 0
          center:
            lat: [SNIP]
            lng: [SNIP]
          pitch: 0
          zoom: -0.3706434003783814
        geometryType: Point
      readonly: false
      required: false
      sort: 10
      special: null
      translations: null
      validation: null
      validation_message: null
      width: full
    schema:
      name: location
      table: [SNIP]
      data_type: POINT
      default_value: null
      max_length: null
      numeric_precision: null
      numeric_scale: null
      is_nullable: true
      is_unique: false
      is_primary_key: false
      is_generated: false
      generation_expression: null
      has_auto_increment: false
      foreign_key_table: null
      foreign_key_column: null
```

Thanks for the extension btw!
